# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: yarn install
  displayName: 'Install yarn packages'

- script: yarn run build
  displayName: 'Build'
  failOnStderr: true

- script: |
   yarn run test:ci
   yarn run posttest
  displayName: "Run tests"

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: 'test/junit.xml'
  displayName: 'Publish test results'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage/'
  displayName: 'Publish code coverage results'

- task: CopyFiles@2
  inputs:
    contents: |
      **/build/**
      firebase.json
    targetFolder: $(Build.ArtifactStagingDirectory)
  displayName: 'Copy build artifacts'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'